ci:
  autoupdate_schedule: monthly
  autofix_commit_msg: "ci: [pre-commit.ci] auto fixes [...]"
  autoupdate_commit_msg: "ci: [pre-commit.ci] autoupdate"
  autofix_prs: true
  autoupdate_branch: ''
  submodules: false

default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending

  # -   repo: https://github.com/doublify/pre-commit-rust
  #     rev: master
  #     hooks:
  #       - id: fmt
  #       - id: cargo-check
  #       - id: clippy
