version: 2

sphinx:
  builder: html
  configuration: rpycocotools/docs/conf.py
  fail_on_warning: true

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"
    rust: "1.64"

python:
  install:
    - requirements: rpycocotools/requirements-doc.txt
    - method: pip
      path: rpycocotools
