[package]
name = "rust_coco_tools"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.117"
serde_derive = "1.0.117"
serde_json = "1.0.59"
clap = { version = "4.0.29", features = ["derive"] }
