version: 2

sphinx:
  builder: html
  configuration: conf.py
  fail_on_warning: true

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
    rust: "1.55"

python:
  install:
    - requirements: docs/requirements-doc.txt
    - method: pip
      path: .
