name: rpycocotools python CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - "rpycocotools/**.py"
      - "rpycocotools/**.rs"
      - .github/workflows/ci-python-rpycocotools.yaml
      - rpycocotools/pyproject.toml
  pull_request:
    paths:
      - "rpycocotools/**.py"
      - "rpycocotools/**.rs"
      - .github/workflows/ci-python-rpycocotools.yaml
      - rpycocotools/pyproject.toml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rpycocotools

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "**/requirements*.txt"
      - run: pip install --upgrade pip
      - run: pip install -r requirements/requirements-dev.txt
      - run: ruff .
      - run: pip install -r requirements/requirements-flake8.txt
      - run: flake8 .

  python-typing-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rpycocotools

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "**/requirements*.txt"
      - run: pip install -r requirements/requirements-dev.txt -r requirements/requirements-test.txt  -r requirements/requirements-benchmarks.txt
      - run: pip install ../rpycocotools-stubs
      - run: pyright .

  python-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rpycocotools

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "**/requirements*.txt"
      - run: pip install -r requirements/requirements-test.txt
      - run: pip install .
      - run: python -m pytest . -vv
