name: rpycocotools python CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - "rpycocotools/**.py"
      - "rpycocotools/**.rs"
      - .github/workflows/ci-python-rpycocotools.yaml
      - rpycocotools/pyproject.toml
  pull_request:
    paths:
      - "rpycocotools/**.py"
      - "rpycocotools/**.rs"
      - .github/workflows/ci-python-rpycocotools.yaml
      - rpycocotools/pyproject.toml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rpycocotools

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "**/requirements*.txt"
      - run: pip install -r requirements/requirements-dev.txt
      - run: ruff .
      - run: pip install flake8 flake8-bugbear flake8-builtins flake8-comprehensions flake8-docstrings flake8-quotes pep8-naming flake8-import-order flake8-noqa flake8-broken-line flake8-commas Flake8-pyproject
      - run: flake8 .

  python-type-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rpycocotools

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "**/requirements*.txt"
      - run: pip install -r requirements/requirements-dev.txt
      - run: pyright .

  python-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rpycocotools

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "**/requirements*.txt"
      - run: pip install -r requirements/requirements-test.txt
      - run: pip install .
      - run: python -m pytest . -vv
